### ISSUE TITLE
Error with minimal example

### ISSUE THREAD

**Issue by dbaumgaertner** [dengwirda/find-poly#1]
Dear @dengwirda,

I stumbled across your algorithm and find it very promising for an application I have in mind. Really nice piece of work with an excellent example by the way. 

Trying to adapt it to my case with Matlab 2019b, I ran into an error with your algorithm. I am sure, I am violating here an assumption or missing a setting, but after trying quite some time, I couldn't figure it out. Now I am wondering if you could help me in this regard? Below you find a simple minimal example to reproduce the error. It consists of only three polygons and three query points/vertices. Would it be possible for you to have a quick look into it and maybe provide me with advice in terms of why it's failing and how to fix it? Any help is appreciated.

Thank you very much in advance and best wishes.

```
% Input
nodes = {[-0.000165000,-0.000137425;
          -0.000165000,-0.000134575;
          -0.000163500,-0.000134575;
          -0.000163500,-0.000137425;
          -0.000165000,-0.000137425];
         [-0.000165000,-0.000129425;
          -0.000165000,-0.000126575;
          -0.000163500,-0.000126575;
          -0.000163500,-0.000129425;
          -0.000165000,-0.000129425];
         [-0.000165000,-0.000121425;
          -0.000165000,-0.000118575;
          -0.000163500,-0.000118575;
          -0.000163500,-0.000121425;
          -0.000165000,-0.000121425]};
      
edges = {[1,2;2,3;3,4;4,5];
         [1,2;2,3;3,4;4,5];
         [1,2;2,3;3,4;4,5]};
     
vertices= 1e-3*[-0.164,-0.136;
                -0.164,-0.1;
                -0.164,-0.12];

% Plot setup
figure
for i = 1:size(nodes,1)
    plot(nodes{i}(:,1),nodes{i}(:,2))
    hold on
end
scatter(vertices(:,1),vertices(:,2),'x')

% Run search
[iptr,indx] = findpoly(nodes,edges,vertices);
```

**Comment by dengwirda** [comment]
Thanks @dbaumgaertner, this does indeed seem to be a bug, due to the latest [`inpoly`](https://github.com/dengwirda/inpoly) updates not appearing here inside `find-poly`. I'll push some updates...

**Comment by dbaumgaertner** [comment]
Great, thanks a lot for your quick feedback! I'll give it a shot once you pushed the changes.

**Comment by dengwirda** [comment]
Okay, that issue should be resolved in the latest `find-poly`. Let me know how you go with this @dbaumgaertner.

**Comment by dbaumgaertner** [comment]
That does the trick. Thank you very much @dengwirda for the update. Now I can give that idea a try. Just to add: I very much like the fact that the algorithm is not just fast but can handle arbitrary combinations of points and polygons!
